//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using GEA.Back_end.Employees.Models;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace GEA.Back_end.Company.Models
{

    
    public partial class GeaEntities : DbContext
    {
        public GeaEntities()
            : base("name=GeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPANIES> Company { get; set; }
    }
}
