//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace GEA.Back_end.Employees.Models
{

    public partial class EMPLOYEES
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cpf { get; set; }
        public int FunctionId { get; set; }
        public int CompanyId { get; set; }
        public string Phone { get; set; }
        public DateTime CreatedWehn { get; set; }
    }
}
